### ISSUE TITLE
addmoney command

### ISSUE THREAD

**Issue by Draenaii** [TGRHavoc/fivem-serverVote#1]
I've tried to use this resource but it doesn't work so well. Whenever someone votes, and checks their vote, the server cmd says that there is no such command as addmoney. I've tried replacing it with different commands but it also didn't work. I think the problem is that the command in the resource is not listed in the cmdlist of my FXServer. Please help me fix this.

**Comment by TGRHavoc** [comment]
What? You do realise those are just examples, right? I don't even think there's anything that allows people to have money in FiveM. If there is, try installing that?

If you remove the "money" commands but keep the say ones, does the resource work as expected? Do you see a message in game about the player voting?

**Comment by Draenaii** [comment]
The 'say' command works perfectly. Except, since there is no money command supported in FiveM how is the resource expected to give someone money when they have voted?

**Comment by TGRHavoc** [comment]
Did you just gloss over what I said in the first paragraph?

> You do realise those are just examples, right? I don't even think there's anything that allows people to have money in FiveM. If there is, try installing that?

**Comment by TGRHavoc** [comment]
Closing as this isn't an issue. Install a resource that adds the commands you want to use or, just remove the "money" commands from the config. 

If you want "money" on your server, look for a resource that adds it
